## Introducción SQL

### Intro Bases de datos

Para introducir el mundo de las bases de datos, entendamos el contexto donde se manejan.

Imaginemos que tenemos un excel, sin embargo este excel es especial, es un excel que tiene información muy importante, y muchas personas del trabajo usan su información, por ejemplo, datos de hospitales, la cantidad de personas que van de forma mensual, el costo promedio, su dirección y mucha más.

Como todos usan esta información, todos deben tener su copia del archivo, o bajar alguna que esté online para luego poder usarla, un gran desafío con esta metodología es la actualización de la información, si cada persona que trabaja tiene acceso a otra información de algún otro hospital, o quiere añadir una nueva columna por ejemplo, con la cantidad de personas estimada que hay alrededor de 1km de distancia, ¿como vamos a añadir esa información?

Si cada persona tiene información diferente, cada una realizaría cambios, y seguidamente alguien, tendría que tomar todos esos excels y hacerlos uno, es un trabajo lento y difícil, hay varios desafíos con esta metodología:

* Nada asegura que tengamos toda la información de un hospital, si no tenemos algún dato como la cantidad de pacientes, y luego lo sabemos, hay que darse el trabajo de unir.
* Supongamos que se lleva tiempo con este mecanismo, y se realizó lo siguiente, cuando se quiere hacer una versión nueva, se piden los excels a todos, y se pone a un equipo a unir todos los datos, ya se hizo la versión 1 y 2, ahora va la 3, sin embargo, de todos los excels, notas que algunos son de la versión 1...., a algunos se les olvidó bajar la version nueva, sin embargo, estos excels igual pueden tener información nueva, así que de todas maneras hay que construir el nuevo excel manejando varias versiones diferentes del mismo documento, con tal vez incluso, diferentes formatos o estructura de datos.

Tener documentos compartidos y esenciales no es un trabajo fácil ni trivial, tener un buen manejo de información es vital para muchos proyectos.

Con el tiempo, puede ser necesario incluir nuevos datos para nuevos proyectos, ahora ya no vamos a necesitar solo hospitales, vamos a necesitar establecimientos educacionales, locales de bienes indispensables y varios más.

Y si va todo bien, vamos a pasar de analizar y necesitar no solamente datos de una localidad o región, podriamos ya empezar a necesitar datos nacionales o mundiales, ahora tenemos en nuestro excel tantas pestañas con temas y datos, que el PC ya no los logra abrir, tal vez uno muy potente, aun así estamos en problemas, aun podemos dividir este excel en carpetas, cada carpeta con un tema, luego un excel con un tema, y cada pestaña con un subtema, es un arreglo que funcionara, al menos para abrir los documentos si son lo suficientemente chicos, y esta división de datos.

Ahora, tenemos mucha información, muchas carpetas, muchos excels, un gran equipo que se encarga de sacar nuevas versiones, el cual de vez en cuando hay que contratar más personas por el aumento en la cantidad de información, aun así, debería haber una manera más práctica, una forma más fácil de gestionar todo este tema de la información.

Incluso si podemos almacenarla y ordenarla, difícilmente podremos analizar bien la cantidad de datos que usamos, o realizar análisis de datos cruzados, por ejemplo comparar relaciones entre la cantidad de población de un sector, sus recursos económicos y la cantidad de personas que ingresan al hospital, incluso si el excel tiene esa función, difícilmente funcione bien con muchos datos, no es que falte aprender más excel, simplemente no está diseñado para esa cantidad de datos, y para el uso que le estamos dando.

En este contexto entran los sistemas para bases de datos, este programa es un super excel, el cual está diseñado para manejar miles de millones de datos y en parte poder trabajarlos, este sistema tiene la siguiente estructura:

* Servidor (Super excel, que contendrá muchos excels normales)
    + Base de datos 1 (Carpeta 1)
    + Base de datos 2 (Carpeta 2)
        + Esquema 1 (Excel 1 de la Carpeta 2)
        + Esquema 2 (Excel 2 de la Carpeta 2)
            + Tabla 1 (Pestaña 1 del Excel 2)
            + Tabla 2 (Pestaña 2 del Excel 2)

Podemos ver que un servidor de bases de datos o sistema de bases de datos ya nos permite darle un orden a toda la información, tal vez no sea una alternativa perfecta como cuando podemos tener muchas carpetas dentro de carpetas, pero igual podemos jugar con los nombres de las tablas, si se usan nomenclaturas como "hospitales_", y "_2020", o "_entrada" para ordenar las tablas, por ejemplo para, si tenemos datos sobre a qué hora entra una persona al hospital, y a que hora sale, tendríamos dos tablas:

“datos_personas” Columnas de Rut, Nombre, Apellido
“hospital_entrada_salida_2020”. Rut, Fecha/Hora entrada, Fecha/hora salida

Si viéramos solamente la tabla de los datos del hospital podría uno toparse con lo siguiente, "Espera, a veces quiero poder tener el nombre y apellido, poder ver solamente el rut no me sirve"

Perfectamente razonable, ahora recordemos, las bases de datos se especializan en tratar grandes cantidades de datos, y tienen muchos temas cubiertos, y este es uno de ellos, si escribiéramos el nombre y apellido en cada tabla tendríamos información repetida, y no es eficiente actualizar cada tabla por separado, por eso, las bases de datos te permiten decirle, "une ambas tablas, y usa el rut para unirlas", de esa manera tendríamos una sola tabla con Rut, Nombre, Apellido, Fecha/Hora entrada y Fecha/Hora salida.

## Introducción Parte 2

Ha sido bastante texto para la parte 1, asi que vamos a dividir, ya que a pesar que aún estamos introduciendo, la temática y narrativa cambiara un poco desde acá.

Retomemos desde la base de datos, la cual tiene una estructura en el Servidor, Base de datos, Esquema y Tabla, vamos a indicar ahora en términos generales que soluciona un servidor.

Los servidores permiten lo siguiente:

* Una gran cantidad de personas pueden leer acceder a una tabla de forma simultánea y pueden
    + Leer los datos
    + Editar los datos
    + Trabajar con los datos
* Crear funciones en la base de datos, estas ya traen funciones para obtener por ejemplo la suma de los valores de una columna, igual que el excel, si no nos bastan las funciones que trae, siempre podemos hacer más y que estén disponibles.
* Se pueden crear usuarios y permisos, para ajustar quienes pueden hacer que en cada base de datos, esquema o tabla.

Como pueden notar, los sistemas de bases de datos son muy útiles y potentes, si pusiéramos el ejemplo anterior.

Tenemos una Tabla con los datos de un hospital, y un integrante del equipo ahora tiene cuantas personas entran y salen del mismo, puede ingresar los datos a la tabla, y desde ese momento esa actualizacion estara disponible para todas las personas de forma casi instantánea, no se necesita revisar, unir ni nada parecido.

Hay varios puntos como respaldos, que pasa si alguien se equivoca y borra/cambia un dato o tabla, sin embargo, eso lo dejaremos para más adelante, ya que hay alternativas, no se preocupen.

Es hora de ver uno de los puntos más controversiales para quienes ven una base de datos, mientras que el Excel está pensado para cosas pequeñas (para hoy en día, la capacidad del excel es pequeño), es importante ver y tratar datos de forma visual, ya que es rápido y amigable con el usuario.

Los sistemas de base de datos no tienen interfaz gráfica, divide y conquistaras, con tal de poder llegar a un modelo eficiente para tratar tantos datos, el excel se dividió.

El servidor se encargará de gestionar datos por detrás (ingresarlos, transformarlos y entregarlos).

Alguna otra aplicación se usará para poder verlos o darles un tratamiento diferente, de hecho, podemos abrir una base de datos con excel.

Este punto, en parte puede deberse a que, tiene sentido ver datos en un excel cuando no son muchos, de esa manera visualmente controlas, regulas que hay y que no hay, sin embargo, si tienes miles y millones de datos, no tiene mucho sentido verlos, lo mas seguro es que ingreses datos, quieras ver una parte, y editar alguna parte.

Ahora, no tenemos interfaz gráfica, ¿cómo nos relacionamos con el sistema de bases de datos?

Los sistemas de bases de datos tienen datos, y lo que nos importa es cómo obtenerlos y tratarlos, poder hacer "Consultas", y se creó una sintaxis, un lenguaje para poder realizar estas consultas, ese lenguaje se llama SQL.

El lenguaje usualmente es bastante intuitivo, pero de a ratos es tan larga la consulta que escribimos que puede ser complicado de usar, porque es difícil de visualizar y conectar todo lo escrito.

Sin embargo no nos estaremos, el lenguaje está, pero no necesitas saber casi nada, y aveces nada para poder leer datos, por ejemplo, si pones los datos de una tabla, con su base de datos, usuario y clave a un excel, podrás leerla, ¿como lee el excel estos datos? Por detrás se comunica con el lenguaje SQL para recuperar los datos que quieres ver, y luego te los muestra, los edita y al guardar, el Excel vuelve a usar el lenguaje SQL para decirle al sistema de base de datos que realice los cambios en la tabla.

De la misma forma para quienes programan, muchos lenguajes tienen librerías y módulos, que hacen automáticamente esto, de esa manera no necesitas saber SQL.

Aun así, por más que eso esté automático, no siempre es suficiente, si necesitas trabajar con muchos datos, necesitas relaciones más complejas, te importa que el trabajo se hecho bien y rápido, vas a necesitar aprender SQL, es un lenguaje que incluso en su conocimiento más básico, da una gran ventaja sobre muchas aplicaciones automáticas, recuperar las información justa y necesaria para trabajar, es clave en un mundo donde la información abunda.

Una mirada superficial a lo que permite SQL:

Los datos y tablas pueden ser:

* Relacionados (por ejemplo unir tablas por una o varias columnas)
* Filtrar datos
* Hacer cálculos
* Construir tablas nuevas en base a otras
* Funciones personalizadas

¿Entonces tendré que aprender SQL para poder hacer todo bien? Depende, es bueno tener idea sobre como las bases de datos, sin embargo, siempre puedes dividir el trabajo, si hay algo que necesitas, puedes hablar con alguien más técnico que lo haga y desarrolle, luego usas esa eficiente caja negra que te pasaron, la ventaja del CIT ahí es que es multidisciplinario.



